' Rotor Framework Task
import "pkg:/source/libs/rotorFramework/RotorFrameworkTask.bs"

' Import common contants
import "pkg:/components/app/common/intentTypes.bs"

sub init()
    m.top.functionName = "task"
    m.appFw = new Rotor.FrameworkTask()
end sub


' EXAMPLE FOR creating model, reducer and dispatcer withouth any additional bs files.
sub task()

    ' MODEL
    initialState = {
        isReady: false
    }
    modelInstance = new Model(initialState)

    ' REDUCER
    reducerInstance = new Reducer()
    reducerInstance.reducer = function(state, intent)

        if intent.type = IntentTypes.Sleep.START
            sleep(intent.payload?.duration * 1000 ?? 1000)
            state.isReady = true
        end if

        return state
    end function

    ' DISPATCHER
    m.sleepDispatcher = Rotor.createDispatcher("sleep", modelInstance, reducerInstance)

    m.appFw.sync()

end sub
