namespace Models
    class UserModel extends Model

        state = {
            userName: "Guest User",
            userType: "guest",
            personalization: {
                locale: "en_US"
            },

            ' Available languages - to this user
            languageKeys: [
                ' "de_DE",
                "en_US",
                ' "es_ES",
                ' "fr_FR",
                ' "hu_HU",
                ' "it_IT",
                ' "nl_NL"
                ' "pl_PL",
                ' "pt_PT",
                ' "sv_SE"
            ]
        }

    end class

end namespace
