
namespace Reducers

    class UserReducer extends Reducer

        override function reducer(state, intent)

            if intent.type = IntentTypes.User.SET_ACTIVE_LANGUAGE_KEY
                state.personalization.locale = intent.payload.locale

            else intent.type = IntentTypes.User.SET_ACTIVE_THEME_KEY
                state.personalization.activeThemeKey = intent.payload.activeThemeKey

            end if

            return state
        end function

    end class

end namespace
